workflows:
  ios-unsigned-build:
    name: HelloWorld iOS Unsigned Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          sudo gem install xcodeproj
      - name: Build C++ Core
        script: |
          echo "Building C++ Core..."
          # C++ core is compiled directly by Xcode via generate_project.rb
      - name: Generate Xcode Project
        script: |
          ruby generate_project.rb
      - name: Build iOS App
        script: |
          xcodebuild archive \
            -project HelloWorld.xcodeproj \
            -scheme HelloWorld \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/HelloWorld.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES
      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -R build/HelloWorld.xcarchive/Products/Applications/HelloWorld.app Payload/
          zip -r HelloWorld.ipa Payload
    artifacts:
      - HelloWorld.ipa
